language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update

install:
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind

script:
  - make
  - make cppcheck
  - make valgrind
